### PR TITLE
Fix for GNU extended filenames

### LINKED ISSUE #16: Possible fix for GNU extended filenames
Looks like this line:
https://github.com/vidstige/ar/blob/e0275f79281c1cc5d9f3f4622b8de3f76cf95a42/ar/archive.py#L78

Should be:
```py
end = data.find(b"\n", start)
```

After this fix, I was able to work with my files.
@vidstige please check it out

### PR DESCRIPTION
**Pull request by vshymanskyy**
Closes #16

### CODE REVIEW

**Comment by vidstige** [comment]
The solution is a bit far out in my opinion. It would make more sense to split only on NUL (`\0`) and then rstrip newline (`\n`)

**Review by vidstige — APPROVED** [review]
Aha, the tests were wrong 🙈 Nice find. Thank you for your contribution.

I would probably have gone for something simpler like so
```
def lookup(data: bytes, offset: int) -> str:
    start = offset
    positions = (data.find(c, start) for c in (b"\x2F", b"\x00"))
    end = min(position for position in positions if position >= 0)
    return data[start:end].decode()
```

But all good. 💯

**Comment by vidstige** [comment]
Python 3.7 does not like your variable name "c"  :see_no_evil: 

However, I feel the name is a reasonable one.

Feel free
* To ignore it by adding it here: https://github.com/vidstige/ar/blob/master/.pylintrc#L4
* Or rename the variable.

**Comment by vshymanskyy** [comment]
I think the functional style is less readable here.
`rstrip` won't help here...
I've pushed the variable name change.

**Comment by vshymanskyy** [comment]
@vidstige I have further simplified the `lookup`. This should be good to merge.

**Comment by vshymanskyy** [comment]
By the way, here's what I use it for: https://github.com/micropython/micropython/issues/14430#issuecomment-2344693510

**Comment by vshymanskyy** [comment]
@vidstige I have modified the `test_roundtrip` to also cover long filenames.
Hopefully we can merge it soon.

**Comment by vidstige** [comment]
Very cool project! I wrote this library myself when I wanted to some analysis of static files. Thanks for this high quality contribution. 🚀

**Comment by vshymanskyy** [comment]
Thanks for creating the library in the first place!
I would be grateful of you could push a new version to pip.☺️

**Comment by vshymanskyy** [comment]
Awesome, thanks!

**Pull request merged**
